-- MySQL Script generated by MySQL Workbench
-- Fri May 24 13:11:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` BLOB NOT NULL,
  `email_iv` BLOB NOT NULL,
  `email_hash` BLOB NOT NULL,
  `password` BLOB NULL,
  `password_salt` BLOB NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` BLOB NOT NULL,
  `last_name_iv` BLOB NOT NULL,
  `birth_date` INT NULL,
  `gender` VARCHAR(25) NULL,
  `blood_type` BLOB NULL,
  `blood_type_iv` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_hash_UNIQUE` (`email_hash` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TREATMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TREATMENT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` BLOB NOT NULL,
  `title_iv` BLOB NOT NULL,
  `start_date` BLOB NOT NULL,
  `start_date_iv` BLOB NOT NULL,
  `end_date` BLOB NULL,
  `end_date_iv` BLOB NULL,
  `diagnosis` BLOB NULL,
  `diagnosis_iv` BLOB NULL,
  `category` BLOB NULL,
  `category_iv` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TREATMENT_USER_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_TREATMENT_USER`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEDICINE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MEDICINE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` BLOB NOT NULL,
  `name_iv` BLOB NOT NULL,
  `name_hash` BLOB NOT NULL,
  `active_substance` BLOB NULL,
  `active_substance_iv` BLOB NULL,
  `active_substance_hash` BLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_hash_UNIQUE` (`name_hash` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TREATMENT_MEDICINE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TREATMENT_MEDICINE` (
  `treatment_id` INT NOT NULL,
  `medicine_id` INT NOT NULL,
  `dose` INT NULL,
  `administration_route` VARCHAR(25) NULL,
  `initial_dosing_time` INT NOT NULL,
  `dosage_frequency_hours` INT NOT NULL,
  `dosage_frequency_minutes` INT NOT NULL,
  INDEX `fk_TREATMENT_MEDICINE_TREATMENT1_idx` (`treatment_id` ASC) VISIBLE,
  INDEX `fk_TREATMENT_MEDICINE_MEDICINE1_idx` (`medicine_id` ASC) VISIBLE,
  PRIMARY KEY (`treatment_id`, `medicine_id`),
  CONSTRAINT `fk_TREATMENT_MEDICINE_TREATMENT1`
    FOREIGN KEY (`treatment_id`)
    REFERENCES `mydb`.`TREATMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TREATMENT_MEDICINE_MEDICINE1`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `mydb`.`MEDICINE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MEDICAL_APPOINTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MEDICAL_APPOINTMENT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `treatment_id` INT NOT NULL,
  `subject` VARCHAR(250) NULL,
  `date_time` BLOB NOT NULL,
  `date_time_iv` BLOB NOT NULL,
  `place` VARCHAR(50) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MEDICAL_APPOINTMENT_TREATMENT1_idx` (`treatment_id` ASC) VISIBLE,
  CONSTRAINT `fk_MEDICAL_APPOINTMENT_TREATMENT1`
    FOREIGN KEY (`treatment_id`)
    REFERENCES `mydb`.`TREATMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NOTIFICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NOTIFICATION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `treatment_id` INT NULL,
  `medicine_id` INT NULL,
  `medical_appointment_id` INT NULL,
  `timestamp` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_NOTIFICATION_MEDICINE1_idx` (`medicine_id` ASC) VISIBLE,
  INDEX `fk_NOTIFICATION_TREATMENT1_idx` (`treatment_id` ASC) VISIBLE,
  INDEX `fk_NOTIFICATION_MEDICAL_APPOINTMENT1_idx` (`medical_appointment_id` ASC) VISIBLE,
  CONSTRAINT `fk_NOTIFICATION_MEDICINE1`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `mydb`.`MEDICINE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTIFICATION_TREATMENT1`
    FOREIGN KEY (`treatment_id`)
    REFERENCES `mydb`.`TREATMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTIFICATION_MEDICAL_APPOINTMENT1`
    FOREIGN KEY (`medical_appointment_id`)
    REFERENCES `mydb`.`MEDICAL_APPOINTMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALLERGY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALLERGY` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` BLOB NOT NULL,
  `name_iv` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ALLERGY_USER1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_ALLERGY_USER1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PREVIOUS_MEDICAL_CONDITION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PREVIOUS_MEDICAL_CONDITION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` BLOB NOT NULL,
  `name_iv` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PREVIOUS_MEDICAL_CONDITION_USER1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_PREVIOUS_MEDICAL_CONDITION_USER1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GUIDELINE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GUIDELINE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `treatment_id` INT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(250) NULL,
  `num_order` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_STEP_TREATMENT1_idx` (`treatment_id` ASC) VISIBLE,
  CONSTRAINT `fk_STEP_TREATMENT1`
    FOREIGN KEY (`treatment_id`)
    REFERENCES `mydb`.`TREATMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MULTIMEDIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MULTIMEDIA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `guideline_id` INT NOT NULL,
  `type` VARCHAR(25) NOT NULL,
  `uri` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MULTIMEDIA_STEP1_idx` (`guideline_id` ASC) VISIBLE,
  CONSTRAINT `fk_MULTIMEDIA_STEP1`
    FOREIGN KEY (`guideline_id`)
    REFERENCES `mydb`.`GUIDELINE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SYMPTOM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SYMPTOM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `treatment_id` INT NOT NULL,
  `description` BLOB NOT NULL,
  `description_iv` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SYMPTOM_TREATMENT1_idx` (`treatment_id` ASC) VISIBLE,
  CONSTRAINT `fk_SYMPTOM_TREATMENT1`
    FOREIGN KEY (`treatment_id`)
    REFERENCES `mydb`.`TREATMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QUESTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`QUESTION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `treatment_id` INT NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_QUESTION_TREATMENT1_idx` (`treatment_id` ASC) VISIBLE,
  CONSTRAINT `fk_QUESTION_TREATMENT1`
    FOREIGN KEY (`treatment_id`)
    REFERENCES `mydb`.`TREATMENT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
